name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub (optional)
      # You can skip this step if you don't plan to push
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t quick-vantage:latest .

    # Optionally, push to DockerHub
    # - name: Push Docker image
    #   run: |
    #     docker tag quick-vantage:latest yourdockerhubusername/quick-vantage:latest
    #     docker push yourdockerhubusername/quick-vantage:latest
